spring:
  datasource:
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite:${SQLITE_DB_PATH:C:\sqlite\sqlite.db}
  web:
    resources:
      static-locations: classpath:/static/
  mvc:
    static-path-pattern: /**

server:
  port: 9999

springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs